### ISSUE TITLE
Зависает, если подать на вход больше 5 урлов

### ISSUE THREAD

**Issue by vporoshok** [exested/bpm#1]

**Comment by exested** [comment]
а как вы передаете урлы?
вот мой вывод:
```
/work/go/test_task/bpm $ echo -e "https://reddis.com\nhttps://google.com\nhttps://yandex.ru\nhttps://mail.com\nhttps://reddit.com\nhttps://github.com\nhttps://bitbucket.org/\nhttps://golang.org/" | go run main.go 
Count for https://google.com: 7
Count for https://yandex.ru: 3
Count for https://github.com: 6
Count for https://bitbucket.org/: 0
Count for https://mail.com: 0
Count for https://reddit.com: 21
Count for https://golang.org/: 20
Count for https://reddis.com: 0
Total count: 57
The End

```

**Comment by vporoshok** [comment]
Прошу прощения, не так в голове скомпилировал. Программа действительно не зависает, но параллельно оказывается запущено столько горутин, сколько входных данных.

**Comment by exested** [comment]
`commonChan := make(chan struct{}, maxGoroutines)`
строка 45, вот тут объявляется буферизируемый канал 
`commonChan <- struct{}{}`
строка 54, блокируется когда в канале уже 5 элементов то есть 5 горутин запущено, когда освобождается тогда запускается ещё одна горутина
`<-commonChan`
строка 39, тут освобождается канал горутин

**Comment by vporoshok** [comment]
Но горутина на этом не завершается

**Comment by exested** [comment]
> Но горутина на этом не завершается

потому что не закрывается канал?

**Comment by vporoshok** [comment]
потому что выхода из функции не происходит, а значит хранится фрейм стека, локальные переменные и не закрытый ридер ответа, а значит занятый сокет в ОС.

**Comment by exested** [comment]
> потому что выхода из функции не происходит, а значит хранится фрейм стека, локальные переменные и не закрытый ридер ответа, а значит занятый сокет в ОС.

из функции main или из функции горутины? разве горутина не завершается после выполнения всех инструкций? 
я соглашусь что подход с break не очень красивый и возможно не правильный, поэтому я переделал работу через WaitGroup

**Comment by vporoshok** [comment]
Ок, проблема в 40-й строчке. Там происходит запись в небуферизированный канал, которая просто останавливает выполнение до тех пор, пока не появится горутина, читающая из этого канала. Таким образом на 1000 входных данных будет 1000 ждущих горутин.

**Comment by exested** [comment]
Согласен с тем что при в этом месте будет блокироваться и накапливаться большое количество горутин, нужно было или Scan запускать в отдельной горутине или чтение из канала в отдельной. Переделал.

**Comment by vporoshok** [comment]
да, всё отлично!
